package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"net/http"

	"connectrpc.com/connect"

	generated "cmk/generated/graphql"
	designv1 "cmk/generated/merchandise/design/v1"
	rpcdesign "cmk/generated/merchandise/design/v1/designv1connect"
)

// Get is the resolver for the get field.
func (r *queryResolver) Get(ctx context.Context, id string) (*generated.Design, error) {
	client := rpcdesign.NewDesignServiceClient(http.DefaultClient, "http://localhost:4000")
	res, err := client.Get(ctx, connect.NewRequest(&designv1.GetRequest{Id: id}))
	if err != nil {
		return nil, err
	}
	design := &generated.Design{
		CreatedAt:       res.Msg.Design.CreatedAt.String(),
		UpdatedAt:       res.Msg.Design.UpdatedAt.String(),
		ID:              res.Msg.Design.Id,
		Item:            res.Msg.Design.Item,
		Color:           res.Msg.Design.Color,
		ProductCategory: res.Msg.Design.ProductCategory,
		Metal:           res.Msg.Design.Metal,
		MetalRate:       res.Msg.Design.MetalRate,
		ImageURL:        res.Msg.Design.ImageUrl,
		DesignerID:      &res.Msg.Design.DesignerId,
		ParentID:        &res.Msg.Design.ParentId,
	}

	design.Stones = make([]*generated.Stone, len(res.Msg.Design.Stones))
	for i, stone := range res.Msg.Design.Stones {
		design.Stones[i] = &generated.Stone{
			Parcel: stone.Parcel,
			Pieces: int(stone.Pieces),
			Carat:  stone.Carat,
		}
	}
	design.Histories = make([]*generated.Design, len(res.Msg.Design.Histories))
	for i, history := range res.Msg.Design.Histories {
		design.Histories[i] = &generated.Design{
			CreatedAt:       history.CreatedAt.String(),
			UpdatedAt:       history.UpdatedAt.String(),
			ID:              history.Id,
			Item:            history.Item,
			Color:           history.Color,
			ProductCategory: history.ProductCategory,
			Metal:           history.Metal,
			MetalRate:       history.MetalRate,
			ImageURL:        history.ImageUrl,
			DesignerID:      &history.DesignerId,
			ParentID:        &history.ParentId,
		}
	}

	return design, nil
}

// GetAll is the resolver for the getAll field.
func (r *queryResolver) GetAll(ctx context.Context) ([]*generated.Design, error) {
	client := rpcdesign.NewDesignServiceClient(http.DefaultClient, "http://localhost:4000")
	res, err := client.GetAll(ctx, connect.NewRequest(&designv1.GetAllRequest{}))
	if err != nil {
		return nil, err
	}

	designs := make([]*generated.Design, len(res.Msg.Designs))
	for i, design := range res.Msg.Designs {
		designs[i] = &generated.Design{
			CreatedAt:       design.CreatedAt.String(),
			UpdatedAt:       design.UpdatedAt.String(),
			ID:              design.Id,
			Item:            design.Item,
			Color:           design.Color,
			ProductCategory: design.ProductCategory,
			Metal:           design.Metal,
			MetalRate:       design.MetalRate,
			ImageURL:        design.ImageUrl,
			DesignerID:      &design.DesignerId,
			ParentID:        &design.ParentId,
		}

		stones := make([]*generated.Stone, len(design.Stones))
		for _, stone := range design.Stones {
			stones = append(stones, &generated.Stone{
				Parcel: stone.Parcel,
				Pieces: int(stone.Pieces),
				Carat:  stone.Carat,
			})
		}
		designs[i].Stones = stones

		histories := make([]*generated.Design, len(design.Histories))
		for _, history := range design.Histories {
			histories = append(histories, &generated.Design{
				CreatedAt:       history.CreatedAt.String(),
				UpdatedAt:       history.UpdatedAt.String(),
				ID:              history.Id,
				Item:            history.Item,
				Color:           history.Color,
				ProductCategory: history.ProductCategory,
				Metal:           history.Metal,
				MetalRate:       history.MetalRate,
				ImageURL:        history.ImageUrl,
				DesignerID:      &history.DesignerId,
				ParentID:        &history.ParentId,
			})
		}
		designs[i].Histories = histories
	}
	return designs, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
